yogavidya/apps/books/urls.py
from django.urls import path
from .views import (
	BookListView,
	BookCreateView,
	BookDetailView,
	BookUpdateView,
	BookDeleteView,

)

app_name="books"

urlpatterns = [
	path('', BookListView.as_view(), name='list'),
	path('create/', BookCreateView.as_view(), name='create'),
	path('<slug:slug>', BookDetailView.as_view(), name='detail'),
	path('<int:id>/update', BookUpdateView.as_view(), name='update'),
	path('<int:id>/delete', BookUpdateView.as_view(), name='delete'),
]

yogavidya/apps/core/urls.py
from django.contrib import admin
from django.urls import include,re_path, path
from .views import(
    IndexTemplateView
)

app_name = 'core'

urlpatterns = [
	re_path(r"^.*$", IndexTemplateView.as_view(), name="home_auth")
  #path('', IndexTemplateView.as_view(), name='home_auth'),
]

yogavidya/apps/pages/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import(
    page_list,
    page_create,
    page_detail,
    page_update,
    page_delete,
)

app_name = 'pages'

urlpatterns = [
    path('', page_list, name='list'),
    # ex: /category/5/
    path('p/<slug:slug>', page_detail, name='detail'),
    path('create/', page_create, name='create'),
    path('<int:pk>/edit/',page_update, name='update'),
    path('<int:pk>/delete/',page_delete, name='delete'),
]

yogavidya/apps/profiles/api/urls.py
from django.urls import path
from yogavidya.apps.profiles.api import views as prov


urlpatterns = [
	path("user/", prov.CurrentUserAPIView.as_view(), name="current-user"),
	path("user/information/", prov.UserInformationAPIView.as_view(), name="current-user"),
	path("members/", prov.MemberListView.as_view(), name="members"),
	path("teachers/", prov.TeacherListView.as_view(), name="teachers"), 
	path("teachers/<slug:slug>/", prov.TeacherProfileView.as_view(), name="teachers") 
]

yogavidya/urls.py
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.urls import include, path, re_path
from django_registration.backends.one_step.views import RegistrationView
from django.contrib.auth.views import PasswordResetConfirmView
from yogavidya.apps.profiles.forms import YogaUserForm
from yogavidya.apps.core.views import IndexTemplateView
from django.conf.urls.static import static 
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.static import serve  
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)            
from .views import home
from yogavidya.apps.articles import views
from yogavidya.apps.videolessons import views
from rest_auth.registration.views import VerifyEmailView, RegisterView
from yogavidya.apps.profiles.api.views import ConfirmEmailView
from baton.autodiscover import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('baton/', include('baton.urls')),
    path('accounts/register/',
            RegistrationView.as_view(
                form_class=YogaUserForm,
                success_url="/"
            ), name="django_registration_register"),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                    template_name="account/password_reset.html"), 
    name='password_reset_confirm'),
    path('accounts/',
            include('django_registration.backends.one_step.urls')),
    path('accounts/',
            include('django.contrib.auth.urls')),
    
    
    path(_('articles/'), include('yogavidya.apps.articles.urls', namespace='articles')),
    path(_('pages/'), include('yogavidya.apps.pages.urls', namespace='pages')),
    path(_('books/'), include('yogavidya.apps.books.urls', namespace='merchandises')),
    path(_('videolessons/'), include('yogavidya.apps.videolessons.urls', namespace='videolessons')),
    path(_('profiles/'), include('yogavidya.apps.profiles.urls', namespace='profiles')),
]
urlpatterns += [
    
    path('api/',
        include("yogavidya.apps.articles.api.urls")),
    path('api/',
        include("yogavidya.apps.books.api.urls")),
    path('api/',
        include("yogavidya.apps.categories.api.urls")),
    path('api/',
        include("yogavidya.apps.filemanager.api.urls")),
    path('api/',
        include("yogavidya.apps.locations.api.urls")),
    path('api/',
        include("yogavidya.apps.pages.api.urls")),
    path('api/',
        include("yogavidya.apps.profiles.api.urls")),
    path('api/',
        include("yogavidya.apps.statusses.api.urls")),
    path('api/',
        include("yogavidya.apps.tags.api.urls")),
    path('api/',
        include("yogavidya.apps.videolessons.api.urls")),
    path('api-auth/',
		include("rest_framework.urls")),
    path('api/rest-auth/',
		include("rest_auth.urls")),
    path('api/rest-auth/registration/',
		include("rest_auth.registration.urls")),

    path('api/rest-auth/registration/verify-email/', VerifyEmailView.as_view(),
     name='account_email_verification_sent'),
    path('api/rest-auth/password/reset/', VerifyEmailView.as_view(),
     name='account_email_verification_sent'),
    #re_path(r'^account-confirm-email/(?P<key>[-:\w]+)/$', VerifyEmailView.as_view(
    #            template_name="account/email_confirm.html"
    #        ),
    re_path(r'^rest-auth/registration/account-confirm-email/(?P<key>[-:\w]+)/$', 
                ConfirmEmailView.as_view(), name='account_confirm_email'),

    # NEW: custom verify-token view which is not included in django-rest-passwordreset
    #path('reset-password/verify-token/', CustomPasswordTokenVerificationView.as_view(), name='password_reset_verify_token'),
    # NEW: The django-rest-passwordreset urls to request a token and confirm pw-reset
    #path('api/reset-password/', include('django_rest_passwordreset.urls', namespace='password_reset')),
    path('api/password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),

    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT
    }),
    
    #re_path(r'^img/(?P<path>.*)$', serve, {
    #    'document_root': settings.VUE_IMAGES_ROOT
    #}),
    re_path(r'^.*$', IndexTemplateView.as_view(), name="home"),

    
]

       # add this

if settings.DEBUG:     
    urlpatterns += staticfiles_urlpatterns()  
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

yogavidya/apps/articles/forms.py
from django import forms
#from ckeditor_uploader.widgets import CKEditorUploadingWidget
from yogavidya.apps.articles.models import Article, ArticleComment



class ArticleModelForm(forms.ModelForm):
	#content = forms.CharField(widget=CKEditorUploadingWidget)
	class Meta:
	   model=Article
	   fields = [ "title", "slug","filter_order", "author", "categories", "tags", "content","excerpt","index_page","image",'total_likes', 'users_like', "draft","publish",]

class ArticleCommentModelForm(forms.ModelForm):
	class Meta:
	   model=ArticleComment
	   fields = ["content"]

yogavidya/apps/books/forms.py
from django import forms
from yogavidya.apps.books.models import Book, BookComment



class BookModelForm(forms.ModelForm):
	class Meta:
	   model=Book
	   fields = [
					"title",
					"slug",
					"categories",
					"tags",
					"content",
					"excerpt",
					"index_page",
					"image",
					"draft",
					"publish"]

class BookCommentModelForm(forms.ModelForm):
	class Meta:
	   model=BookComment
	   fields = [ "content"]

yogavidya/apps/categories/forms.py
from django import forms
from django.contrib import admin
from django.db import models
from django.forms import Textarea, ModelForm
from django.forms.widgets import TextInput
from yogavidya.apps.categories.models import Category

 

class CategoryModelForm(forms.ModelForm):

    class Meta:
       model=Category
       fields = [ "title", "slug", "color","image"]
       widgets = {
            'color': TextInput(attrs={'type': 'color'}),
        }

yogavidya/apps/profiles/forms.py
from django_registration.forms import RegistrationForm
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError
from django.forms.widgets import Select
from yogavidya.apps.profiles.models import  Student, Question, Answer, StudentAnswer
from yogavidya.apps.locations.models import City, Country, State
from PIL import Image
from django.core.files import File
from django.forms.widgets import TextInput
from django.contrib.auth import authenticate
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.translation import ugettext_lazy as _
from django.template import loader
from django.utils.encoding import force_bytes
from yogavidya.apps.profiles.models import User
class TeacherSignUpForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		model = User

	def save(self, commit=True):
		user = super().save(commit=False)
		user.is_teacher = True
		if commit:
			user.save()
		return user

	

class StudentSignUpForm(UserCreationForm):
	 #interests = forms.ModelMultipleChoiceField(
	#    queryset=Subject.objects.all(),
	#    widget=forms.CheckboxSelectMultiple,
	#    required=True
	#)
	email = forms.EmailField(required=True, label='Email')
	
	def __init__(self, *args, **kwargs):
				super(StudentSignUpForm, self).__init__(*args, **kwargs)

				for fieldname in ['username', 'password1', 'password2']:
						self.fields[fieldname].help_text = None


	class Meta(UserCreationForm.Meta):
		model = User
		fields = ('email','username', 'password1', 'password2')

	@transaction.atomic
	def save(self):
		user = super().save(commit=False)
		user.is_student = True
		user.email = self.cleaned_data.get('email')
		user.username = self.cleaned_data.get('username')
		user.save()
		student = Student.objects.create(user=user)
		#student.interests.add(*self.cleaned_data.get('interests'))
		return user



class UserPhotoForm(forms.ModelForm):
 
	class Meta:
		model = User
		fields = ['image']
		
class UserPhotoEditForm(forms.ModelForm):
	x = forms.FloatField(widget=forms.HiddenInput())
	y = forms.FloatField(widget=forms.HiddenInput())
	width = forms.FloatField(widget=forms.HiddenInput())
	height = forms.FloatField(widget=forms.HiddenInput())

	class Meta:
		model = User
		fields = ['image', 'x', 'y', 'width', 'height',]

	def save(self):
		image = super(UserPhotoEditForm, self).save()

		x = self.cleaned_data.get('x')
		y = self.cleaned_data.get('y')
		w = self.cleaned_data.get('width')
		h = self.cleaned_data.get('height')

		image = Image.open(image.file)
		cropped_image = image.crop((x, y, w+x, h+y))
		resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
		resized_image.save(image.file.path)

		return image

class UserProfileForm(forms.ModelForm):
	#state = forms.ModelChoiceField(queryset=State.objects.all(),)
	birth_date = forms.DateField(input_formats=['%d/%m/%Y'])
	widget=forms.DateInput(format='%d/%m/%Y',)

	class Meta:
		model = User
		fields = (
					'bio',
					'city',
					'country',
					'first_name',
					'last_name',
					'location',
					'phone',
					'gender',
					'birth_date',
					'terms',
					'image',
					'height_field',
					'width_field'
				 )
		
	def __init__(self, *args, **kwargs):
		super(UserProfileForm, self).__init__(*args, **kwargs)
		self.fields['country'].queryset = Country.objects.all()
		#self.fields['state'].queryset = State.objects.all()
		#self.fields['state'] = State(queryset=State.objects.all(),widget=forms.Select(attrs={'class': ''}),)
		self.fields['city'].queryset = City.objects.all()
		self.fields['birth_date'].widget.attrs.update({'class': 'datepicker form-control'})


def load_cities(request):
    country_id = request.GET.get('country')
    cities = City.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'hr/city_dropdown_list_options.html', {'cities': cities})
    
class BiggerUserProfileForm(forms.ModelForm): 

	#state = forms.ModelChoiceField(queryset=State.objects.all(),)
	birth_date = forms.DateField(input_formats=['%d/%m/%Y'])
	widget=forms.DateInput(format='%d/%m/%Y',)
	x = forms.FloatField(widget=forms.HiddenInput())
	y = forms.FloatField(widget=forms.HiddenInput())
	width = forms.FloatField(widget=forms.HiddenInput())
	height = forms.FloatField(widget=forms.HiddenInput())
	class Meta:
		model = User
		fields = (
					'bio',
					'city',
					'country',
					'first_name',
					'last_name',
					'location',
					'phone',
					'gender',
					'birth_date',
					'terms',
					'image',
					'hobbies',
					'fav_music',
					'fav_tv',
					'fav_books',
					'fav_movies',
					'fav_routes',
					'x', 'y', 'width', 'height',
				 )
		
	def __init__(self, *args, **kwargs):
		super(UserProfileForm, self).__init__(*args, **kwargs)
		self.fields['country'].queryset = Country.objects.all()
		#self.fields['state'].queryset = State.objects.all()
		#self.fields['state'] = State(queryset=State.objects.all(),widget=forms.Select(attrs={'class': ''}),)
		self.fields['city'].queryset = City.objects.all()
		self.fields['birth_date'].widget.attrs.update({'class': 'datepicker form-control'})

	def clean_image(self):
		image = self.cleaned_data.get('image', False)
		if not self.instance.image == image:
			# validate image
			return None
	
	def save(self):
		image = super(UserProfileForm, self).save()

		x = self.cleaned_data.get('x')
		y = self.cleaned_data.get('y')
		w = self.cleaned_data.get('width')
		h = self.cleaned_data.get('height')

		image = Image.open(photo.file)
		cropped_image = image.crop((x, y, w+x, h+y))
		resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
		resized_image.save(photo.file.path)

		return image


# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
	first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
	last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
	email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
		
class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

class RegisterForm(forms.Form):
	pass

class PasswordResetForm(forms.Form):
    email = forms.EmailField(label=_("Email"), max_length=254)

    def save(self, domain_override=None,
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """
        from django.core.mail import send_mail
        UserModel = get_user_model()
        email = self.cleaned_data["email"]
        active_users = UserModel._default_manager.filter(
            email__iexact=email, is_active=True)
        for user in active_users:
            # Make sure that no email is sent to a user that actually has
            # a password marked as unusable
            if not user.has_usable_password():
                continue
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            c = {
                'email': user.email,
                'domain': domain,
                'site_name': site_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': 'https' if use_https else 'http',
            }
            subject = loader.render_to_string(subject_template_name, c)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            email = loader.render_to_string(email_template_name, c)
            send_mail(subject, email, from_email, [user.email])
class YogaUserForm(RegistrationForm):

	class Meta(RegistrationForm.Meta):
		model = User
		
class StudentInterestsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('interests', )
        widgets = {
            'interests': forms.CheckboxSelectMultiple
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', )


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one answer as correct.', code='no_correct_answer')


class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')

yogavidya/templates/snippets/header_v1.html
{% load static %}
{% load thumbnail %}
{% load i18n %}
{% load l10n %}
{% load tz %}
<!-- Header-BP -->

<header class="header" id="site-header">

	<div class="page-title">
		<a href="{% url 'home' %}" class="stylish-logo"><h6 class="stylish-fonts">YOGAVIDYA</h6></a>	
	</div>

	<div class="header-content-wrapper">
		<!-- <form class="search-bar w-search notification-list friend-requests">
			<div class="form-group with-button">
				<input class="form-control" placeholder="{% trans 'Search here people or pages...' %}" type="text">
				<button>
					<svg class="olymp-magnifying-glass-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-magnifying-glass-icon"></use></svg>
				</button>
			</div>
		</form>

		<a href="#" class="link-find-friend">Find Friends</a>
	-->
		

		<div class="control-block">
			<a href="{% url 'articles:list' %}" class="link-find-friend">{% trans 'Articles' %}</a>
			<a href="{% url 'videolessons:list' %}" class="link-find-friend">{% trans 'Videolessons' %}</a>
			<a href="{% url 'merchandises:list' %}" class="link-find-friend">{% trans 'Books' %}</a>
			<a href="{% url 'profiles:teachers:teachers_list' %}" class="link-find-friend">{% trans 'Teachers' %}</a>
			<a href="{% url 'profiles:teachers:teachers_info' %}" class="link-find-friend">{% trans "For Teachers"%}</a>
			<a href="{% url 'pages:detail' slug='destek-ol' %}" class="link-find-friend btn-primary btn-sm">{% trans 'Support Us' %}</a>
			<a href="{% url 'profiles:profile_index' %}" class="link-find-friend">{% trans 'My Profile' %}</a>
			<div class="author-page author vcard inline-items more">
				
				<div class="author-thumb">
					{% thumbnail user.image "60x60" crop="center" as im %}
							<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="request.user.username" class="avatar">
					{% endthumbnail %}

					<span class="icon-status online"></span>
					<div class="more-dropdown more-with-triangle">
						<div class="mCustomScrollbar" data-mcs-theme="dark">
							<div class="ui-block-title ui-block-title-small">
								<h6 class="title">{% trans 'Your Account' %}</h6>
							</div>

							<ul class="account-settings">
								<li>
									<a href="{% url 'profiles:profile_settings' %}">

										<svg class="olymp-menu-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-menu-icon"></use></svg>

										<span>{% trans 'Profile Settings' %}</span>
									</a>
								</li>
								<!--
								<li>
								<a href="36-FavPage-SettingsAndCreatePopup.html">
										<svg class="olymp-star-icon left-menu-icon"  data-toggle="tooltip" data-placement="right"   data-original-title="FAV PAGE"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-star-icon"></use></svg>

										<span>Create Fav Page</span>
									</a>
								</li>
								-->
								<li>
									<a href="{% url 'profiles:logout' %}">
										<svg class="olymp-logout-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-logout-icon"></use></svg>

										<span>{% trans "Log Out"%}</span>
									</a>
								</li>
							</ul>

 

							<div class="ui-block-title ui-block-title-small">
								<h6 class="title">{% trans 'Custom Status' %}</h6>
							</div>

							<form class="form-group with-button custom-status">
								<input class="form-control" placeholder="" type="text" value="Space Cowboy">

								<button class="bg-purple">
									<svg class="olymp-check-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-check-icon"></use></svg>
								</button>
							</form>

							<div class="ui-block-title ui-block-title-small">
								<h6 class="title">{% trans 'About YogaVidya'  %}</h6>
							</div>

							<ul>
								<li>
									<a href="{% url 'pages:detail' slug='gizlilik-ve-guvenlik' %}">
										<span>{% trans 'Terms and Conditions'  %}</span>
									</a>
								</li>
								<li>
									<a href="{% url 'pages:detail' slug='rlys-tt-nedir' %}">
										<span>{% trans 'Teacher' %}</span>
									</a>
								</li>
								
								<li>
									<a href="{% url 'pages:detail' slug='gizlilik-ve-guvenlik' %}">
										<span>{% trans 'Contact' %}</span>
									</a>
								</li>
							</ul>
						</div>

					</div>
				</div>
				<a href="{% url 'home' %}" class="author-name fn">
					<div class="author-title">
						{{request.user.first_name}} <svg class="olymp-dropdown-arrow-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-dropdown-arrow-icon"></use></svg>
					</div>
					<span class="author-subtitle">{{request.user.username}}</span>
				</a>
			</div>

		</div>
	</div>

</header>

<!-- ... end Header-BP -->


<!-- Responsive Header-BP -->

<header class="header header-responsive" id="site-header-responsive">

	<div class="header-content-wrapper">
		<ul class="nav nav-tabs mobile-app-tabs" role="tablist">
			<li class="nav-item">
				<a class="nav-link" data-toggle="tab" href="#request" role="tab">
					<div class="control-icon has-items">
						<svg class="olymp-happy-face-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-happy-face-icon"></use></svg>
						<div class="label-avatar bg-blue">6</div>
					</div>
				</a>
			</li>

			<li class="nav-item">
				<a class="nav-link" data-toggle="tab" href="#chat" role="tab">
					<div class="control-icon has-items">
						<svg class="olymp-chat---messages-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-chat---messages-icon"></use></svg>
						<div class="label-avatar bg-purple">2</div>
					</div>
				</a>
			</li>

			<li class="nav-item">
				<a class="nav-link" data-toggle="tab" href="#notification" role="tab">
					<div class="control-icon has-items">
						<svg class="olymp-thunder-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-thunder-icon"></use></svg>
						<div class="label-avatar bg-primary">8</div>
					</div>
				</a>
			</li>

			<li class="nav-item">
				<a class="nav-link" data-toggle="tab" href="#search" role="tab">
					<svg class="olymp-magnifying-glass-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-magnifying-glass-icon"></use></svg>
					<svg class="olymp-close-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-close-icon"></use></svg>
				</a>
			</li>
		</ul>
	</div>

</header>

<!-- ... end Responsive Header-BP -->
<div class="header-spacer"></div>

yogavidya/templates/snippets/top-header-profile.html
{% load static%}
{% load thumbnail %}
{% load i18n %}
{% load l10n %}
{% load tz %}<!-- Top Header-Profile -->
{% block head_css %}
<!-- font -->
<link  rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,500,500i,600,700,800,900|Poppins:200,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900">

{% endblock %}
<div class="container">
	<div class="row">
		<div class="col col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
			<div class="ui-block">
				<div class="top-header">
					<div class="top-header-thumb">
						<img src="{% static 'img/BANNER-1.png' %}" alt="nature">
					</div>
					<div class="profile-section">
						<div class="row">
							<div class="col col-lg-5 col-md-5 col-sm-12 col-12">
								<ul class="profile-menu">
									<li>
										<a href="{% url 'home' %}" class="active">{% trans 'Home' %}</a>
									</li>
									<li>
										<a href="{% url 'profiles:about' %}">{% trans 'About' %}</a>
									</li>
									<li>
										<a href="{% url 'profiles:members' %}">{% trans 'Members' %}</a>
									</li>
								</ul>
							</div>
							<div class="col col-lg-5 ml-auto col-md-5 col-sm-12 col-12">
								<ul class="profile-menu">
									<li>
										<a href="#">{% trans 'Photos' %}</a>
									</li>
									<li>
										<a href="{% url 'videolessons:list' %}">{% trans 'Videos' %}</a>
									</li>
									<li>
										<a href="{% url 'articles:list' %}">{% trans 'Articles' %}</a>
									</li>
									<li>
										<div class="more">
											<svg class="olymp-three-dots-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-three-dots-icon"></use></svg>
											<ul class="more-dropdown more-with-triangle">
												<li>
													<a href="{% url 'profiles:hobbies_settings' %}">{% trans 'Update Your Information' %}</a>
												</li>
											</ul>
										</div>
									</li>
								</ul>
							</div>
						</div>

						<div class="control-block-button">

							<div class="btn btn-control bg-primary more">
								<svg class="olymp-settings-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-settings-icon"></use></svg>

								<ul class="more-dropdown more-with-triangle triangle-bottom-right">
									<li>
										<a href="{% url 'profiles:profile_photo_update' %}" data-toggle="modal" data-target="#update-header-photo">{% trans 'Update Profile Photo' %}</a>
									</li>
									<li>
										<a href="#" data-toggle="modal" data-target="#update-header-photo">{% trans 'Update Header Photo' %}</a>
									</li>
									<li>
										<a href="{% url 'profiles:profile_settings' %}">{% trans 'Account Settings' %}</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="top-header-author">
						<a href="{% url 'profiles:profile_settings' %}" class="author-thumb">
							{% thumbnail user.image "120x120" crop="center" as im %}
				                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
				            {% endthumbnail %}
						</a>
						<div class="author-content">
							<a href="{% url 'home' %}" class="h4 author-name">{{ user.username }}</a>
							<div class="country">{{user.city|default_if_none:""}}</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>