yogavidya/apps/books/urls.py
from django.urls import path
from .views import (
	BookListView,
	BookCreateView,
	BookDetailView,
	BookUpdateView,
	BookDeleteView,

)

app_name="books"

urlpatterns = [
	path('', BookListView.as_view(), name='list'),
	path('create/', BookCreateView.as_view(), name='create'),
	path('<slug:slug>', BookDetailView.as_view(), name='detail'),
	path('<int:id>/update', BookUpdateView.as_view(), name='update'),
	path('<int:id>/delete', BookUpdateView.as_view(), name='delete'),
]

yogavidya/apps/core/urls.py
from django.contrib import admin
from django.urls import include,re_path, path
from .views import(
    IndexTemplateView
)

app_name = 'core'

urlpatterns = [
	re_path(r"^.*$", IndexTemplateView.as_view(), name="home_auth")
  #path('', IndexTemplateView.as_view(), name='home_auth'),
]

yogavidya/apps/pages/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import(
    page_list,
    page_create,
    page_detail,
    page_update,
    page_delete,
)

app_name = 'pages'

urlpatterns = [
    path('', page_list, name='list'),
    # ex: /category/5/
    path('p/<slug:slug>', page_detail, name='detail'),
    path('create/', page_create, name='create'),
    path('<int:pk>/edit/',page_update, name='update'),
    path('<int:pk>/delete/',page_delete, name='delete'),
]

yogavidya/apps/profiles/urls.py
from django.urls import include, path
# -*- coding: utf-8 -*-
from django.conf.urls.i18n import i18n_patterns

from django.utils.translation import gettext_lazy as _
from yogavidya.apps.profiles.views import classroom, students, teachers
from yogavidya.apps.profiles.views.classroom import(
    signup,
    dashboard,
    user_detail,
    user_follow,
    user_list,
    user_login,
    user_register,
    profile_index,
    #logout,
    logout_then_login,
    account_settings,
    personal_information,
    about

)
from yogavidya.apps.profiles.views.students import LoginView
from yogavidya.apps.galleries.views import BasicUploadView

from .views import classroom, students, teachers
app_name = 'profiles'
urlpatterns = [
    path('search/', classroom.search, name='teacher_search'),
    path('users/follow/', user_follow, name='user_follow'),
    path(_('about/'), classroom.UserProfilePageAboutView.as_view(), name='about'),
    path('detail/<str:slug>', classroom.MemberDetailView.as_view(), name='detail'),
    
    path(_('members/'), classroom.UserMembersListView.as_view(), name='members'),
    path(_('photos/'), BasicUploadView.as_view(), name='photos'),
    path(_('settings/'), classroom.UserProfileUpdateView.as_view(), name='profile_update'),
    path(_('profile_index'), classroom.profile_index, name='profile_index'),
    path(_('profile_settings'), classroom.ProfileUpdateView.as_view(), name='profile_settings'),
    path(_('hobbies_settings'), classroom.HobbiesUpdateView.as_view(), name='hobbies_settings'),
    path(_('profile_photo_update'), classroom.PhotoUpdateView.as_view(), name='profile_photo_update'),
    path('profile_photo_alt', classroom.PhotoAltUpdateView.as_view(), name='profile_photo_alt'),
    path('upload_picture', classroom.upload_picture, name='upload_picture'),
    path('update_profile', classroom.update_profile, name='update_profile'),
    path('profile_update', classroom.profile_update, name='profile_update'),
    

    
]





urlpatterns  += [
    
    path('account_settings', account_settings, name='account_settings'),
    path('personal_information', personal_information, name='personal_information'),

    path(_('signup/'), classroom.SignUpView.as_view(), name='signup'),

    path(_('student_login/'), LoginView.as_view(), name='student_login'),
    path(_('teacher_login/'), teachers.LoginView.as_view(), name='teacher_login'),
    path('logout_then_login', logout_then_login, name='logout_then_login'),
    #password related urls

    path('logout/', classroom.LogoutView.as_view(), name='logout'),
    path('users', user_list, name='user_list'),
    path('users/<slug:slug>', user_detail, name='user_detail'),
]


urlpatterns += [

    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.TeachersListView.as_view(), name='teachers_list'),
        path('quiz_list/', teachers.QuizListView.as_view(), name='quiz_change_list'),
        path('info', teachers.TeachersInfoView.as_view(), name='teachers_info'),
        path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
    ], 'classroom'), namespace='teachers')),
]

urlpatterns  += [
    
    path('account_settings', account_settings, name='account_settings'),
    path('personal_information', personal_information, name='personal_information'),

    path(_('signup/'), classroom.SignUpView.as_view(), name='signup'),
    path(_('signup_student/'), students.StudentSignUpView.as_view(), name='student_signup'),
    path(_('signup_teacher/'), teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    path(_('student_login/'), LoginView.as_view(), name='student_login'),
    path(_('teacher_login/'), teachers.LoginView.as_view(), name='teacher_login'),
    path('logout_then_login', logout_then_login, name='logout_then_login'),
    #password related urls

    path('logout/', classroom.LogoutView.as_view(), name='logout'),
    path('users', user_list, name='user_list'),
    path('users/<slug:slug>', user_detail, name='user_detail'),
]

yogavidya/urls.py
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.urls import include, path, re_path
from django_registration.backends.one_step.views import RegistrationView
from django.contrib.auth.views import PasswordResetConfirmView
from yogavidya.apps.profiles.forms import YogaUserForm
from yogavidya.apps.core.views import IndexTemplateView
from django.conf.urls.static import static 
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.static import serve  
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)            
from .views import home
from yogavidya.apps.articles import views
from yogavidya.apps.videolessons import views
from rest_auth.registration.views import VerifyEmailView, RegisterView
from yogavidya.apps.profiles.api.views import ConfirmEmailView
from baton.autodiscover import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('baton/', include('baton.urls')),
    path('accounts/register/',
            RegistrationView.as_view(
                form_class=YogaUserForm,
                success_url="/"
            ), name="django_registration_register"),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                    template_name="account/password_reset.html"), 
    name='password_reset_confirm'),
    path('accounts/',
            include('django_registration.backends.one_step.urls')),
    path('accounts/',
            include('django.contrib.auth.urls')),
    
    
    path(_('articles/'), include('yogavidya.apps.articles.urls', namespace='articles')),
    path(_('pages/'), include('yogavidya.apps.pages.urls', namespace='pages')),
    path(_('books/'), include('yogavidya.apps.books.urls', namespace='merchandises')),
    path(_('videolessons/'), include('yogavidya.apps.videolessons.urls', namespace='videolessons')),
    path(_('profiles/'), include('yogavidya.apps.profiles.urls', namespace='profiles')),
]
urlpatterns += [
    
    path('api/',
        include("yogavidya.apps.articles.api.urls")),
    path('api/',
        include("yogavidya.apps.books.api.urls")),
    path('api/',
        include("yogavidya.apps.categories.api.urls")),
    path('api/',
        include("yogavidya.apps.filemanager.api.urls")),
    path('api/',
        include("yogavidya.apps.locations.api.urls")),
    path('api/',
        include("yogavidya.apps.pages.api.urls")),
    path('api/',
        include("yogavidya.apps.profiles.api.urls")),
    path('api/',
        include("yogavidya.apps.statusses.api.urls")),
    path('api/',
        include("yogavidya.apps.tags.api.urls")),
    path('api/',
        include("yogavidya.apps.videolessons.api.urls")),
    path('api-auth/',
		include("rest_framework.urls")),
    path('api/rest-auth/',
		include("rest_auth.urls")),
    path('api/rest-auth/registration/',
		include("rest_auth.registration.urls")),

    path('api/rest-auth/registration/verify-email/', VerifyEmailView.as_view(),
     name='account_email_verification_sent'),
    path('api/rest-auth/password/reset/', VerifyEmailView.as_view(),
     name='account_email_verification_sent'),
    #re_path(r'^account-confirm-email/(?P<key>[-:\w]+)/$', VerifyEmailView.as_view(
    #            template_name="account/email_confirm.html"
    #        ),
    re_path(r'^rest-auth/registration/account-confirm-email/(?P<key>[-:\w]+)/$', 
                ConfirmEmailView.as_view(), name='account_confirm_email'),

    # NEW: custom verify-token view which is not included in django-rest-passwordreset
    #path('reset-password/verify-token/', CustomPasswordTokenVerificationView.as_view(), name='password_reset_verify_token'),
    # NEW: The django-rest-passwordreset urls to request a token and confirm pw-reset
    #path('api/reset-password/', include('django_rest_passwordreset.urls', namespace='password_reset')),
    path('api/password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),

    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT
    }),
    
    #re_path(r'^img/(?P<path>.*)$', serve, {
    #    'document_root': settings.VUE_IMAGES_ROOT
    #}),
    re_path(r'^.*$', IndexTemplateView.as_view(), name="home"),

    
]

       # add this

if settings.DEBUG:     
    urlpatterns += staticfiles_urlpatterns()  
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

yogavidya/apps/actions/models.py
from django.db import models
#from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

class Action(models.Model):
	user = models.ForeignKey(
				settings.AUTH_USER_MODEL,
				related_name='actions',
				on_delete=models.CASCADE,
				db_index=True)
	verb = models.CharField(max_length=255)
	target_ct = models.ForeignKey(ContentType,
								blank=True,
								null=True,
								on_delete=models.CASCADE,
								related_name='target_obj')
	target_id = models.PositiveIntegerField(null=True,
											blank=True,
											db_index=True)
	target= GenericForeignKey('target_ct', 'target_id')
	created_at = models.DateTimeField(
				auto_now_add=True,
				db_index=True)

	class Meta:
		ordering = ('-created_at',)

yogavidya/apps/categories/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify
from yogavidya.apps.core.utils import generate_random_string
from sorl.thumbnail import ImageField

class Category(models.Model):

    def upload_location(instance, filename):
        #filebase, extension = filename.split(".")
        # return "%s/%s.%s" %(instance.id, instance.id, extension)
        try:
            CategoryModel = instance.__class__
            new_id = CategoryModel.objects.order_by("id").last().id + 1
        except:
            new_id = 1
        return "{} {}".format(new_id, filename)
    # Relations
    # Attributes - Mandatory
    title = models.CharField(
        max_length=200,
        verbose_name=_("title"),
        help_text=_("Enter the Category title"))
    color = models.CharField(max_length=7, default='#007bff')
    slug = models.SlugField(unique=True)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    image = models.ImageField(
        null=True,
        blank=True,
        upload_to=upload_location,
        height_field="height_field",
        width_field="width_field",)
    created_at = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
        verbose_name=("created_at"))
    updated_at = models.DateTimeField(
        auto_now_add=True,
        auto_now=False,
        verbose_name=_("updated_at"),
        help_text=_("Enter a new date"))
    # Attributes - Optional
    # Custom Properties

    # Methods
    def get_absolute_url(self):
        return reverse("categories:detail", kwargs={"slug": self.slug})

 
    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)
    # Meta and String
    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        ordering = ['title', ]
        unique_together = ["title"]

    def __str__(self):
        return "{}".format(self.title)


@receiver(pre_save, sender=Category)
def pre_save_category_receiver(sender, instance, raw, using, **kwargs):
    if instance and not instance.slug:
        slug = slugify(instance.title)
        random_string = generate_random_string()
        instance.slug = slug + "_" + random_string


pre_save.connect(pre_save_category_receiver, sender=Category)

yogavidya/apps/core/models.py
from django.db import models

# Create your models here.

yogavidya/apps/filemanager/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class Data(models.Model):

    file_id = models.AutoField(primary_key=True)
    file = models.FileField(null=True, max_length=255)
    created_at = models.DateTimeField(default = timezone.now)
    def __str__(self):
        return str(self.file.name)

yogavidya/apps/articles/forms.py
from django import forms
#from ckeditor_uploader.widgets import CKEditorUploadingWidget
from yogavidya.apps.articles.models import Article, ArticleComment



class ArticleModelForm(forms.ModelForm):
	#content = forms.CharField(widget=CKEditorUploadingWidget)
	class Meta:
	   model=Article
	   fields = [ "title", "slug","filter_order", "author", "categories", "tags", "content","excerpt","index_page","image",'total_likes', 'users_like', "draft","publish",]

class ArticleCommentModelForm(forms.ModelForm):
	class Meta:
	   model=ArticleComment
	   fields = ["content"]

yogavidya/apps/books/forms.py
from django import forms
from yogavidya.apps.books.models import Book, BookComment



class BookModelForm(forms.ModelForm):
	class Meta:
	   model=Book
	   fields = [
					"title",
					"slug",
					"categories",
					"tags",
					"content",
					"excerpt",
					"index_page",
					"image",
					"draft",
					"publish"]

class BookCommentModelForm(forms.ModelForm):
	class Meta:
	   model=BookComment
	   fields = [ "content"]

yogavidya/apps/categories/forms.py
from django import forms
from django.contrib import admin
from django.db import models
from django.forms import Textarea, ModelForm
from django.forms.widgets import TextInput
from yogavidya.apps.categories.models import Category

 

class CategoryModelForm(forms.ModelForm):

    class Meta:
       model=Category
       fields = [ "title", "slug", "color","image"]
       widgets = {
            'color': TextInput(attrs={'type': 'color'}),
        }

yogavidya/apps/galleries/forms.py
from django import forms
from photologue.models import Gallery, Photo
from yogavidya.apps.galleries.models import GalleryExtended,PhotoExtended
from yogavidya.apps.profiles.models import User
from django.forms import HiddenInput
from django.core.exceptions import ValidationError

from django.contrib import messages

class GalleryModelForm(forms.ModelForm):

	class Meta:
	   model=GalleryExtended
	   fields = ["title" ]

 
	def clean_title(self):
		title = self.cleaned_data['title']
		galleries = Gallery.objects.all()
		for gallery in galleries:
			if gallery.title==title:
				raise ValidationError("You already used this Name")
				messages.error(request, "Name already taken")

		return title


class PhotoModelForm(forms.ModelForm):

	class Meta:
	   model=PhotoExtended
	   fields = [ 'title', 'gallery']

yogavidya/apps/pages/forms.py
from django import forms
from django.contrib import admin
from django.db import models
from yogavidya.apps.pages.models import Page

class PageModelForm(forms.ModelForm):
	class Meta:
	   model=Page
	   fields = [ "title", "slug", "content", "image", "draft","publish"]
 

yogavidya/templates/django_registration/registration_form.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load l10n %}
{% load tz %}
{% block head_title %}YogaVidya{% endblock %}
{% block topbar %} {% include 'snippets/topbar.html' %}{% endblock %}
{% block content %}
<div class="content-bg-wrap"></div>
{% include 'snippets/header-standard.html' %}

<div class="container">
  <div class="row display-flex">
    <div class="col col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
      <div class="landing-content">
        <h1>{% trans "Welcome to the Biggest Yoga Network in the World" %}</h1>
        {% blocktrans %}
        <p>We are second the best and biggest social network with 5 billion active users all around the world. Share you
          thoughts, write blog posts, show your favourite music via Stopify, earn badges and much more!
        </p>
        {% endblocktrans %}
        <a class="btn btn-border c-white" data-toggle="modal" data-target="#membershipConditions">
          {% trans 'See membership conditions' %}
        </a>
        <br>
        <br>
        <hr>
        <p>{% trans 'if you are already member' %} </p>
        <a href="{% url 'profiles:student_login' %}" class="btn btn-md btn-border c-white">{% trans "Login" %}</a>
        

      </div>
    </div>

    <div class="col col-xl-5 col-lg-6 col-md-12 col-sm-12 col-12">

      <!-- Login-Registration Form  -->

      <div class="registration-login-form">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li class="nav-item">
            <a class="nav-link  active" data-toggle="tab" href="#signup-student" role="tab">
              <svg class="olymp-register-icon"><use xlink:href="/static/svg-icons/sprites/icons.svg#olymp-register-icon"></use></svg>
            </a>
      
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
          <div class="tab-pane active" id="signup-student" role="tabpanel" data-mh="log-tab">
            <div class="title h6">{% trans "Register to Rlys" %}</div>
            {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                  <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
              </ul>
            {% endif %}
            
 
            {% if form.errors %}{%endif%}
            <form method="post" action="{% url 'profiles:student_signup' %}" novalidate class="content">

                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}">
                {{ form|crispy }}
                
 
              <button type="submit" class="btn btn-success">{% trans 'Sign up' %}</button>

            </form>
       
          </div>

  
        </div>

      <!-- ... end Login-Registration Form  -->   </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="membershipConditions" tabindex="-1" role="dialog" aria-labelledby="membershipConditions" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="membershipConditionst,tşe">{% trans 'Membership Conditions' %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3>ÜYELİK ŞARTLARI</h3>



        <p>1- Sitemiz gerçek kullanıcılar içindir. 

        <ul>

        <li>- Üyelerimiz gerçek ad, soyad ve profil fotoğrafı kullanmalıdır.</li>



        <li>- Gerçek ad, soyad ve profil fotoğrafı kullanmayan sahte hesaplar kapatılır.</li>

        </ul>
        </p>
        <p>2 - Belirli bir grubu, kişi ya da kişileri rahatsız edecek içerikler paylaşmak ve diğer üyelerin huzurunu bozacak mesajlar göndermek site kuralları gereği üyeliğinizin iptal edilmesine neden olabilir.</p>


        <p>3- Sitemizde bulunan tüm yazılı ve görsel materyeller herhangi bir yerden kopyalanmadan ekibimiz tarafından üretilmiştir. Bu nedenle sitede bulunan her şey telif hakları yasasına göre korunmaktadır. İzinsiz yapılan alıntılar ve kopyalamalar hukuki durumlar yaratacaktır.

        <ul>

        <li>- Bu platform tüm insanlara hizmet etmek için kurulmuştur. Bu nedenle zorunlu bir ödeme şekli mevcut değildir. </li>



        <li>- Platformumuzun daha da faydalı bir hale gelebilmesi için siz de fikirlerinizi, görüşlerinizi ve maddi desteklerinizi bizimle paylaşabilirsiniz. </li>



        <li>- Bu sayede daha çok içerik üretmemize katkıda bulunabilir ve ihtiyacı olan fakat imkanı olmayanların da bu sistemden faydalanmasını sağlayabilirsiniz.</p>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Close' %}</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block footer_content %}
<script type="text/javascript">
  $(document).ready(function() {

    $('body').addClass("landing-page")

  });
</script>

{% endblock %}